server:
  port: 9000
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  application:
    name: helloworld
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      failFast: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      